### ISSUE TITLE
Incorrect probability calculations in Junction Tree algorithm

### ISSUE THREAD

**Issue by dante-ga** [bayesjs/bayesjs#24]
I'm imressed by the performace of the Junction Tree algorithm but I noticed that some of the probabilities it calculates are wrong. Could you please fix this bug? I'm a bit rusty on graph theory. Please see the test result and test files below.

Test result:
```
 FAIL  test/infers/threeCliques.test.ts
  ● infers › 3q network › infers give A False (Junction Tree)

    expect(received).toBe(expected) // Object.is equality

    Expected: "0.5000"
    Received: "0.5467"

      17 |   const given = { A: 'F' }
      18 | 
    > 19 |   expect(infer(network, { B: 'T' }, given).toFixed(4)).toBe('0.5000')
         |                                                        ^
      20 |   expect(infer(network, { C: 'T' }, given).toFixed(4)).toBe('0.1500')
      21 |   expect(infer(network, { D: 'T' }, given).toFixed(4)).toBe('0.5000')
      22 |   expect(infer(network, { E: 'T' }, given).toFixed(4)).toBe('0.5000')

      at infersGiveAFalse (test/infers/threeCliques.test.ts:19:56)
      at Object.<anonymous> (test/infers/threeCliques.test.ts:46:48)
```

File: models/three-cliques.ts
```typescript
import { INode } from '../src/types'

export const a: INode = {
  id: 'A',
  states: ['T', 'F'],
  parents: [],
  cpt: { T: 0.5, F: 0.5 },
}

export const b: INode = {
  id: 'B',
  states: ['T', 'F'],
  parents: ['A'],
  cpt: [
    { when: { 'A': 'T' }, then: { T: 0.5, F: 0.5 } },
    { when: { 'A': 'F' }, then: { T: 0.5, F: 0.5 } },
  ],
}

export const c: INode = {
  id: 'C',
  states: ['T', 'F'],
  parents: ['B'],
  cpt: [
    { when: { 'B': 'T' }, then: { T: 0.1, F: 0.9 } },
    { when: { 'B': 'F' }, then: { T: 0.2, F: 0.8 } },
  ],
}

export const d: INode = {
  id: 'D',
  states: ['T', 'F'],
  parents: ['B', 'C'],
  cpt: [
    { when: { B: 'T', C: 'T' }, then: { T: 0.5, F: 0.5 } },
    { when: { B: 'T', C: 'F' }, then: { T: 0.5, F: 0.5 } },
    { when: { B: 'F', C: 'T' }, then: { T: 0.5, F: 0.5 } },
    { when: { B: 'F', C: 'F' }, then: { T: 0.5, F: 0.5 } },
  ],
}

export const e: INode = {
  id: 'E',
  states: ['T', 'F'],
  parents: ['B', 'C'],
  cpt: [
    { when: { B: 'T', C: 'T' }, then: { T: 0.5, F: 0.5 } },
    { when: { B: 'T', C: 'F' }, then: { T: 0.5, F: 0.5 } },
    { when: { B: 'F', C: 'T' }, then: { T: 0.5, F: 0.5 } },
    { when: { B: 'F', C: 'F' }, then: { T: 0.5, F: 0.5 } },
  ],
}

export const allNodes = [a, b, c, d, e]
```

File: test/infers/threeCliques.test.ts
```typescript
import * as expect from 'expect'

import { IInfer } from '../../src/types'
import { allNodes } from '../../models/three-cliques'
import { createNetwork } from '../../src/utils'
import { inferences } from '../../src'

const {
  enumeration,
  junctionTree,
  variableElimination,
} = inferences

const network = createNetwork(...allNodes)

const infersGiveAFalse = (infer: IInfer) => {
  const given = { A: 'F' }

  expect(infer(network, { B: 'T' }, given).toFixed(4)).toBe('0.5000')
  expect(infer(network, { C: 'T' }, given).toFixed(4)).toBe('0.1500')
  expect(infer(network, { D: 'T' }, given).toFixed(4)).toBe('0.5000')
  expect(infer(network, { E: 'T' }, given).toFixed(4)).toBe('0.5000')
}

const inferencesNames: { [key: string]: IInfer } = {
  Enumeration: enumeration.infer,
  'Junction Tree': junctionTree.infer,
  'Variable Elimination': variableElimination.infer,
}

const tests: { [key: string]: (infer: IInfer) => void } = {
  'infers give A False': infersGiveAFalse,
}

describe('infers', () => {
  describe('3q network', () => {
    const testNames = Object.keys(tests)
    const inferNames = Object.keys(inferencesNames)

    for (const testName of testNames) {
      const method = tests[testName]

      for (const inferName of inferNames) {
        const infer = inferencesNames[inferName]

        it(`${testName} (${inferName})`, () => method(infer))
      }
    }
  })
})
```

**Comment by nolleto** [comment]
Thanks for the report! I will check the Junction Tree algorithm as soon as possible.

**Comment by dante-ga** [comment]
Any progress on this? I'm having a hard time finding a better alternative. If it will be fixed I'll be happy to help out with other issues.

**Comment by nolleto** [comment]
Hey @dante-ga, sorry, I didn't have much time yet. I've checked it today for a half-hour but I couldn't found the error because is a complex algorithm and it's a long time since I implemented it. 

I believe the error is in the method `globalPropagation`, since the cliques are corrected and `getResult` method is fine too.

**Comment by nolleto** [comment]
Hi @dante-ga , I just publish the new version (0.4.2) that fixes this bug 😄 

I will close this issue now 🚀

**Comment by nolleto** [comment]
I've deployed wrongly the `v0.4.2` 😅 
`v0.4.3` is correct 🚀
